# Generated by Django 5.0.14 on 2026-09-09 16:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_category', models.CharField(choices=[('rodent', '啮齿类(大/小鼠)'), ('rabbit', '兔'), ('canine', '犬'), ('swine', '猪'), ('nhp', '非人灵长类'), ('other', '其他')], max_length=16, verbose_name='物种类别')),
                ('operation_area', models.CharField(choices=[('barrier', '屏障环境'), ('surgery', '手术室'), ('prep', '准备间'), ('isolation', '隔离区')], max_length=16, verbose_name='操作区域')),
                ('snapshot', models.JSONField(default=dict, verbose_name='冻结的流程快照')),
                ('status', models.CharField(choices=[('open', '进行中'), ('finalized', '已定稿')], default='open', max_length=16)),
                ('result', models.CharField(choices=[('pending', '待评定'), ('pass', '通过'), ('fail', '未通过')], default='pending', max_length=16)),
                ('score_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='得分率(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('primary_observer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observed_sessions', to=settings.AUTH_USER_MODEL)),
                ('sop_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='sops.sopversion')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='exercises.observationsession')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_code', models.CharField(max_length=32)),
                ('step_name', models.CharField(max_length=64)),
                ('step_order', models.PositiveSmallIntegerField()),
                ('max_points', models.PositiveSmallIntegerField()),
                ('outcome', models.CharField(choices=[('pass', '合格'), ('partial', '部分合格'), ('fail', '不合格'), ('na', '不适用')], max_length=8)),
                ('points_awarded', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('recorded_seq', models.PositiveIntegerField(verbose_name='记录顺序号')),
                ('is_backfilled', models.BooleanField(default=False, verbose_name='是否补录')),
                ('backfill_reason', models.TextField(blank=True, verbose_name='补录原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_records', to='exercises.observationsession')),
            ],
            options={
                'ordering': ['recorded_seq'],
                'unique_together': {('session', 'step_code', 'observer')},
            },
        ),
        migrations.CreateModel(
            name='ObserverConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_code', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('open', '待解决'), ('resolved', '已解决')], default='open', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_outcome', models.CharField(blank=True, choices=[('pass', '合格'), ('partial', '部分合格'), ('fail', '不合格'), ('na', '不适用')], max_length=8)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='exercises.observationsession')),
                ('record_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exercises.steprecord')),
                ('record_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exercises.steprecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CriticalFailConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=32)),
                ('item_description', models.CharField(max_length=256)),
                ('state', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('dismissed', '已排除')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_confirmations', to='exercises.observationsession')),
                ('suggested_by_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exercises.steprecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
