# Generated by Django 5.0.14 on 2026-09-09 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SOPVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=64, verbose_name='设施')),
                ('code', models.CharField(max_length=32, verbose_name='流程代码')),
                ('version', models.CharField(max_length=16, verbose_name='版本号')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('effective_from', models.DateField(verbose_name='生效日期')),
                ('is_current', models.BooleanField(default=False, verbose_name='当前在用')),
                ('retention_days', models.PositiveIntegerField(default=1095, verbose_name='证据保留天数')),
                ('pass_threshold', models.PositiveSmallIntegerField(default=80, verbose_name='通过分数线(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
                'unique_together': {('facility', 'code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SOPStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='顺序')),
                ('code', models.CharField(choices=[('handwash', '洗手'), ('donning', '穿戴'), ('item_transfer', '物品传递'), ('glove_contamination', '手套污染'), ('instrument_layout', '器械摆放'), ('waste_disposal', '废弃物处置')], max_length=32, verbose_name='步骤代码')),
                ('name', models.CharField(max_length=64, verbose_name='步骤名称')),
                ('phase', models.CharField(choices=[('gowning', '更衣'), ('instrument_prep', '器械准备'), ('sterile_field', '无菌区维护'), ('cleanup', '术后清场')], max_length=32, verbose_name='能力域')),
                ('max_points', models.PositiveSmallIntegerField(default=10, verbose_name='满分')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='sops.sopversion')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('version', 'code'), ('version', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CriticalFailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='代码')),
                ('description', models.CharField(max_length=256, verbose_name='描述')),
                ('auto_trigger_step', models.CharField(blank=True, choices=[('handwash', '洗手'), ('donning', '穿戴'), ('item_transfer', '物品传递'), ('glove_contamination', '手套污染'), ('instrument_layout', '器械摆放'), ('waste_disposal', '废弃物处置')], max_length=32, verbose_name='自动提示步骤')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_items', to='sops.sopversion')),
            ],
            options={
                'unique_together': {('version', 'code')},
            },
        ),
    ]
