# Generated by Django 5.0.14 on 2026-09-09 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=512)),
                ('upload_id', models.CharField(blank=True, max_length=128)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(default='video/mp4', max_length=64)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '上传中'), ('completed', '已完成'), ('aborted', '已中止'), ('purged', '已清除(过期)')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retention_until', models.DateTimeField(blank=True, null=True, verbose_name='保留截止')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='exercises.observationsession')),
                ('step_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clips', to='exercises.steprecord')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoAccessAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', '在线查看'), ('download', '下载'), ('denied', '拒绝访问')], max_length=16)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_audits', to='media.videoclip')),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
    ]
